name: Kotlin CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]
  release:
    types: [ published ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        solana: ["1.18.14"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Install Solana
        uses: ./.github/actions/install-solana
        with:
          solana_version: ${{ matrix.solana }}

      - name: Start local validator
        run: solana-test-validator > /dev/null 2>&1 &

      # Build
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test
        run: ./gradlew build -PlocalValidator=true

      - name: Save Test Reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: '**/build/reports'

  publish:
    runs-on: macos-latest
    needs: build
    if: ${{ github.event_name == 'release' && startsWith(github.event.release.tag_name, 'v') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish to Maven Central
        run: ./gradlew clean publishAllPublicationsToMavenCentral --stacktrace -P version=${TAG:1}
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_PUBLISHING_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PUBLISHING_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_CENTRAL_PUBLISHING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_CENTRAL_PUBLISHING_PRIVATE_KEY_PASSWORD }}
          TAG: ${{ github.event.release.tag_name }}
